import { textForm } from "../../interfaces/interface";
export const textInput: Array<textForm> = [
  //! Габариты помещения
  {
    id: 1,
    unit: `м`,
    nameInput: `Введите длину помещения в метрах:`,
    category: `quarters`,
    placeholder: `Длина помещения`,
    input_article: `qua`,
  },
  {
    id: 2,
    unit: `м`,
    nameInput: `Введите ширину помещения в метрах:`,
    category: `quarters`,
    placeholder: `Ширина помещения`,
    input_article: `qua1`,
  },
  {
    id: 3,
    unit: `м`,
    nameInput: `Введите высоту помещения в метрах:`,
    category: `quarters`,
    placeholder: `Высота помещения`,
    input_article: `qua2`,
  },
  //! Месторасположение колонн
  {
    id: 4,
    unit: `шт`,
    nameInput: `Введите количество рядов с колоннами:`,
    category: `column`,
    placeholder: `Количество рядов`,
    input_article: `col`,
  },
  {
    id: 5,
    unit: `шт`,
    nameInput: `Введите количество колонн в одном ряду:`,
    category: `column`,
    placeholder: `Количество колонн`,
    input_article: `col1`,
  },
  {
    id: 6,
    unit: `м`,
    nameInput: `Расстояние от левого края помещения до центра колонны:`,
    category: `column`,
    placeholder: `Расстояние ...`,
    input_article: `col2`,
  },
  {
    id: 7,
    unit: `м`,
    nameInput: `Введите ширину основания колонны:`,
    category: `column`,
    placeholder: `Ширина основания колонны`,
    input_article: `col3`,
  },
  {
    id: 8,
    unit: `м`,
    nameInput: `Введите длину основания колонны:`,
    category: `column`,
    placeholder: `Длина основания колонны`,
    input_article: `col4`,
  },
  {
    id: 9,
    unit: `м`,
    nameInput: `Введите расстояние между основаниями соседних колонн в одном ряду:`,
    category: `column`,
    placeholder: `Расстояние ...`,
    input_article: `col5`,
  },
  //! Габариты бассейнов
  {
    id: 10,
    unit: `₽`,
    nameInput: `Стоимость 1 бассейна:`,
    category: `pool`,
    placeholder: `Стоимость ...`,
    input_article: `pool`,
  },
  {
    id: 11,
    unit: `шт`,
    nameInput: `Введите необходимое количество бассейнов:`,
    category: `pool`,
    placeholder: `Количество бассейнов`,
    input_article: `pool1`,
  },
  {
    id: 12,
    unit: `м`,
    nameInput: `Введите длину бассейна:`,
    category: `pool`,
    placeholder: `Длина бассейна`,
    input_article: `pool2`,
  },
  {
    id: 13,
    unit: `м`,
    nameInput: `Введите высоту бассейна:`,
    category: `pool`,
    placeholder: `Высота бассейна`,
    input_article: `pool3`,
  },
  {
    id: 14,
    unit: `м`,
    nameInput: `Введите диаметр бассейна:`,
    category: `pool`,
    placeholder: `Высота бассейна`,
    input_article: `pool4`,
  },
  {
    id: 15,
    unit: `м`,
    nameInput: `Введите ширину бассейна:`,
    category: `pool`,
    placeholder: `Ширина бассейна`,
    input_article: `pool5`,
  },
  //! Рыбопосадочный материал
  {
    id: 16,
    unit: `гр.`,
    nameInput: `Введите средний вес малька:`,
    category: `fish`,
    placeholder: `Вес малька ...`,
    input_article: `fish`,
  },
  {
    id: 17,
    unit: `₽`,
    nameInput: `Введите стоимость 1 шт:`,
    category: `fish`,
    placeholder: `Стоимость 1 малька ...`,
    input_article: `fish1`,
  },
  {
    id: 18,
    unit: `шт`,
    nameInput: `Введите количество малька, в шт:`,
    category: `fish`,
    placeholder: `Количество малька ...`,
    input_article: `fish2`,
  },
  //!Корм
  {
    id: 20,
    unit: `₽`,
    nameInput: `Введите стоимость корма за 1 кг:`,
    category: `food`,
    placeholder: `Стоимость корма ...`,
    input_article: `food`,
  },
  {
    id: 21,
    unit: `₽`,
    nameInput: `Введите стоимость корма за 1 мешок:`,
    category: `food`,
    placeholder: `Стоимость корма ...`,
    input_article: `food1`,
  },
  {
    id: 22,
    unit: `кг`,
    nameInput: `Введите вес мешка:`,
    category: `food`,
    placeholder: `Вес мешка ...`,
    input_article: `food2`,
  },

  //! коммунальные расходы
  {
    id: 23,
    unit: `₽`,
    nameInput: `Стоимость электроэнергии:`,
    category: `expenses`,
    placeholder: `Цена за 1 кВт `,
    input_article: `exp`,
  },
  {
    id: 24,
    unit: `₽`,
    nameInput: `Стоимость аренды за м²:`,
    category: `expenses`,
    placeholder: `Цена за 1 м² `,
    input_article: `exp1`,
  },
  {
    id: 25,
    unit: `₽`,
    nameInput: `Стоимость аренды за все помещение:`,
    category: `expenses`,
    placeholder: `Стоимость аренды `,
    input_article: `exp2`,
  },
  {
    id: 26,
    unit: `₽`,
    nameInput: `Стоимость покупки помещения:`,
    category: `expenses`,
    placeholder: `Стоимость ... `,
    input_article: `exp3`,
  },
  {
    id: 27,
    unit: `₽`,
    nameInput: `Стоимость водоснабжения за 1  м³:`,
    category: `expenses`,
    placeholder: `Стоимость за 1 м³ `,
    input_article: `exp3`,
  },
];
